printWidth: 100
singleQuote: true
semi: false
bracketSpacing: false
tabWidth: 4
arrowParens: 'always'
trailingComma: 'none'
overrides:
    - files: 'package.json'
      options:
          tabWidth: 2
